### ISSUE TITLE
Invoking fir results in error

### ISSUE THREAD

**Issue by ArthurZ** [dnasseri/fir#24]
I installed `fir` in **Vagrant** and then when I invoke it receive [errors](https://pastebin.com/UmJf6KRY)

**Comment by ronan-mch** [comment]
I have encountered this problem as well after installing on Ubuntu 16.04
```
~$ gem install fir
~$ fir

/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/repl_state.rb:6:in `require_relative': /home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:191: syntax error, unexpected '.' (SyntaxError)
      !(OPTIONAL_DO_TOKENS.include?(stack.last&.word) &&
                                                ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:192: syntax error, unexpected '.'
        (token.position.y == stack.last&.position&.y))
                                         ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:197: syntax error, unexpected '.'
      stack.last&.word != 'when'
                  ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:202: syntax error, unexpected '.'
      return false unless stack.last&.word == 'when'
                                      ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:208: syntax error, unexpected '.'
      return false unless stack.last&.word == 'when'
                                      ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:214: syntax error, unexpected '.'
      return false unless stack.last&.word == 'if'
                                      ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:224: dynamic constant assignment
    Token = Struct.new(:word, :position)
           ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:225: dynamic constant assignment
    Position = Struct.new(:x, :y)
              ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:226: dynamic constant assignment
    IndentBlock = Struct.new(:indents, :executable?)
                 ^
/home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/indent.rb:228: syntax error, unexpected end-of-input, expecting keyword_end
	from /home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir/repl_state.rb:6:in `<top (required)>'
	from /home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir.rb:8:in `require_relative'
	from /home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/lib/fir.rb:8:in `<top (required)>'
	from /home/ronan/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ronan/.rbenv/versions/2.1.4/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ronan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/fir-repl-0.1.1/bin/fir:5:in `<top (required)>'
	from /home/ronan/.rbenv/versions/2.1.4/bin/fir:23:in `load'
	from /home/ronan/.rbenv/versions/2.1.4/bin/fir:23:in `<main>'
```

**Comment by jfrank3220** [comment]
Closing, https://github.com/dnasseri/fir/pull/25 adds version information and 2.1.4 is no supported
