### ISSUE TITLE
undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by bestjane** [dnasseri/fir#32]
platform: mac
operate: input 'els' then input table key fatal.
![7c5b3ba8-10d0-4568-afbb-8b6373119ff5](https://user-images.githubusercontent.com/8843246/35543093-292597dc-059e-11e8-8e44-90c61a119fa7.png)

**Comment by h35514n** [comment]
Another example:

```
~ % fir
(fir)> class Dog
(fir)*   def speak
(fir)*     puts "arf"
(fir)*   end
(fir)> end
=> :speak

(fir)> Dog.spTraceback (most recent call last):
        60: from ~/.asdf/installs/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
        59: from ~/.asdf/installs/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
        58: from ~/.asdf/installs/ruby/2.6.0/bin/fir:23:in `<main>'
        57: from ~/.asdf/installs/ruby/2.6.0/bin/fir:23:in `load'
        56: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/bin/fir:6:in `<top (required)>'
        55: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:21:in `start'
        54: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        53: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        52: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        51: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        50: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        49: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        48: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        47: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        46: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        45: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        44: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        43: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        42: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        41: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        40: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        39: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        38: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        37: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        36: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        35: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        34: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        33: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        32: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        31: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        30: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        29: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        28: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        27: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        26: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        25: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        24: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        23: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        22: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        21: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        20: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        19: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        18: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        17: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        16: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        15: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        14: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        13: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        12: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        11: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
        10: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
         9: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
         8: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
         7: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
         6: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
         5: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:53:in `perform'
         4: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:52:in `perform'
         3: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir.rb:54:in `block in perform'
         2: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir/repl_state.rb:33:in `transition'
         1: from ~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir/key_command/key_command.rb:45:in `execute'

~/.asdf/installs/ruby/2.6.0/lib/ruby/gems/2.6.0/gems/fir-repl-0.1.1/lib/fir/key_command/tab_command.rb:15:in `execute_hook': undefined method `split' for nil:NilClass (NoMethodError)
```
